apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fridiks-no
resources:
  - ../../../base
commonLabels:
  app.kubernetes.io/name: fint-kontroll-orgunit-factory
  app.kubernetes.io/instance: fint-kontroll-orgunit-factory_bfk_no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: fint-kontroll
  fintlabs.no/team: bas
  fintlabs.no/org-id: fridiks.no
patches:
  - patch: |-
      - op: replace
        path: "/spec/orgId"
        value: "fridiks.no"
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "fridiks-no.kontroll.*"
      - op: replace
        path: "/spec/kafka/acls/1/topic"
        value: "fridiks-no.kontroll.*"
      - op: replace
        path: "/spec/env/2/value"
        value: "fridiks-no-fint-kontroll-orgunit-factory"
    target:
      kind: Application
      name: fint-kontroll-orgunit-factory

