fint:
  application-id: fint-kontroll-orgunit-factory
  cache:
    defaultCacheEntryTimeToLiveMillis: 518400000
    defaultCacheHeapSize: 1000000
  kafka:
    topic:
      org-id: ${fint.org-id}
      domain-context: kontroll
    application-id: ${fint.application-id}
  kontroll:
    orgunit:
      publishing:
        initial-delay: 20000
        fixed-delay: 25000
spring:
  kafka:
    consumer:
      group-id: ${fint.application-id}
  profiles:
     include:
       - observability
  logging:
    level:
      root: INFO
      org.apache.kafka: INFO
      no.fintlabs.cache.ehcache.FintEhCacheEventLogger: WARN
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam