apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-kontroll-orgunit-factory
  namespace: fintlabs-no
spec:
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-kontroll-orgunit-factory:latest
  imagePullPolicy: Always
  env:
    - name: fint.kontroll.orgunit.publishing.initial-delay
      value: '20000'
    - name: fint.kontroll.orgunit.publishing.fixed-delay
      value: '25000'
    - name: spring.kafka.consumer.group-id
      value: 'fint-kontroll-orgunit-factory'
    - name: fint.kontroll.orgunitdistance.publishing.initial-delay
      value: '50000'
    - name: fint.kontroll.orgunitdistance.publishing.fixed-delay
      value: '150000'
  kafka:
    enabled: true
    acls:
      - topic: 'fintlabs-no.kontroll.*'
        permission: read
      - topic: 'fintlabs-no.kontroll.*'
        permission: admin
